import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClusterProvider, networkType } from "@/providers/cluster-provider"
import { RecoilProvider } from "@/providers/recoil-privoder";
import { SolanaProvider } from "@/providers/solana-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RecoilProvider>
          <ClusterProvider
            network={
              (process.env.NEXT_PUBLIC_NETWORK as networkType) || "mainnet"
            }
          >
            <SolanaProvider>{children}</SolanaProvider>
          </ClusterProvider>
        </RecoilProvider>
      </body>
    </html>
  );
}
